/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;


import Controllers.EmpleadoDAO;
import Models.Empleado;
import Models.Persona;
import Security.cripto;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public final class frmEmpleado extends javax.swing.JInternalFrame {
    EmpleadoDAO oemp=new EmpleadoDAO("Empleado.txt");
    //daoEmpleado oEmp = new daoEmpleado("Empleado.txt");
    DefaultListModel listCod = new DefaultListModel();
    DefaultListModel listNom = new DefaultListModel();
    DefaultListModel listApe = new DefaultListModel();
    DefaultListModel listCarg = new DefaultListModel();
    DefaultListModel listCOD = new DefaultListModel();
    DefaultListModel listnio = new DefaultListModel();
    Persona per = new Empleado();   
    cripto crip = new cripto();
    DateTimeFormatter formato_Fec = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    public int deleteEmp;
    public frmEmpleado() {
        initComponents();
        txtCod.setVisible(false);
        edit(false);
        carga_model();
        llena();
        estado_btn(false,true,false,false, true);
        per= oemp.obtener(0);
        System.out.println(""+per.toString()+"\t"+per.getNombre());
    }
    
    private void carga_model(){
        listCodigo.setModel(listCod);
        listNombres.setModel(listNom);
        listApellidos.setModel(listApe);
        ListCargo.setModel(listCarg);
        ListCod.setModel(listCOD);
        ListAnio.setModel(listnio);
    }
    private void limpiar_model(){
        listCod.removeAllElements();
        listNom.removeAllElements();
        listApe.removeAllElements();
        listCarg.removeAllElements();
        listCOD.removeAllElements();
        listnio.removeAllElements();
    }
    private void edit(boolean estado){
        txtDNI.setEnabled(estado);
        txtNombre.setEnabled(estado);
        txtApellido.setEnabled(estado);
        cbxCargo.setEnabled(estado);
        txtCod.setEnabled(estado);
        txtContrasena.setEnabled(estado);
    }
    private void limpiar(){
        txtDNI.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        cbxCargo.setSelectedIndex(0);
        txtCod.setText("");
        txtContrasena.setText("");
    }

    private void llena(){
        if (oemp.tamaño() == 0) {
            JOptionPane.showMessageDialog(this, "Lista sin Elementos!", "Validar", 2);
        } else {
            limpiar_model();
            //(int DNI, String nombre, String apellido,String anio, int codigo, String cargo, int estado,int codD, String contraseña)
            for (int i = 0; i < oemp.tamaño(); i++) {
                listCod.addElement(oemp.obtener(i).getDNI());
                listNom.addElement(oemp.obtener(i).getNombre());
                listApe.addElement(oemp.obtener(i).getApellido());
                listCarg.addElement(((Empleado)oemp.obtener(i)).getCargo());
                if (((Empleado) oemp.obtener(i)).getCargo().equalsIgnoreCase("Dentinta")) {
                    listCOD.addElement(((Empleado)oemp.obtener(i)).getCodD());
                } else {
                    listCOD.addElement(" ");
                }
                listnio.addElement(oemp.obtener(i).getAnio());
                
            }
        }
    }
    private void estado_btn(boolean btnG,boolean btnN,boolean btnM,boolean btnE, boolean btnS){
        btnGuardar.setEnabled(btnG);
        btnNuevoEmp.setEnabled(btnN);
        btnEditarEmp.setEnabled(btnM);
        btnEliminarEmp1.setEnabled(btnE);
        btnSalir.setEnabled(true);
    }
    private int validad(String dni, String nom, String ape, String cargo, String pass){
        int i =0;
        if(dni.equals("")){
           i++; 
        }
        if(nom.equals("")){
           i++; 
        }
        if(ape.equals("")){
           i++; 
        }
        if(cargo.isEmpty()){
           i++; 
        }
        if(pass.isEmpty()){
           i++; 
        }
        return i;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jpopEdit = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btnNuevoEmp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxCargo = new javax.swing.JComboBox<>();
        txtCod = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        btnGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCodigo = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listNombres = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listApellidos = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListCargo = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListCod = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnEliminarEmp1 = new javax.swing.JButton();
        btnEditarEmp = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        ListAnio = new javax.swing.JList<>();

        jpopEdit.setText("Enviar");
        jpopEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpopEditActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jpopEdit);

        setTitle("Formulario Cliente");

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));

        btnNuevoEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/new-copy-50.png"))); // NOI18N
        btnNuevoEmp.setText("Nuevo");
        btnNuevoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEmpActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo Generado");

        txtCodigo.setEditable(false);
        txtCodigo.setColumns(8);
        txtCodigo.setText("1");
        txtCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos Generales"));

        txtNombre.setColumns(12);
        txtNombre.setText("falta boton editar");
        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombres"));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtApellido.setColumns(12);
        txtApellido.setText("validar dni repetido");
        txtApellido.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellidos"));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        jLabel3.setText("cargo");

        cbxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asistente", "Dentinta" }));
        cbxCargo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCargoItemStateChanged(evt);
            }
        });

        txtCod.setBorder(javax.swing.BorderFactory.createTitledBorder("CoD"));

        txtDNI.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI"));
        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDNIKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIKeyTyped(evt);
            }
        });

        txtContrasena.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(txtApellido)
                        .addComponent(txtCod)
                        .addComponent(txtDNI))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtContrasena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save-50.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnNuevoEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnNuevoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addGap(12, 12, 12))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Empleados"));

        listCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI"));
        listCodigo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCodigo.setComponentPopupMenu(jPopupMenu1);
        listCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCodigoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listCodigo);

        listNombres.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombres"));
        listNombres.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listNombres.setEnabled(false);
        listNombres.setFocusable(false);
        jScrollPane2.setViewportView(listNombres);

        listApellidos.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellidos"));
        listApellidos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listApellidos.setEnabled(false);
        jScrollPane3.setViewportView(listApellidos);

        ListCargo.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargo"));
        ListCargo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListCargo.setEnabled(false);
        jScrollPane4.setViewportView(ListCargo);

        ListCod.setBorder(javax.swing.BorderFactory.createTitledBorder("COD"));
        ListCod.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListCod.setEnabled(false);
        jScrollPane5.setViewportView(ListCod);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEliminarEmp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        btnEliminarEmp1.setText("Eliminar");
        btnEliminarEmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmp1ActionPerformed(evt);
            }
        });

        btnEditarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit-32.png"))); // NOI18N
        btnEditarEmp.setText("editar");
        btnEditarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnEditarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnEliminarEmp1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnEliminarEmp1)
                    .addComponent(btnEditarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        ListAnio.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Ingreso"));
        ListAnio.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListAnio.setEnabled(false);
        jScrollPane6.setViewportView(ListAnio);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyPressed
        int key = evt.getKeyChar();
        boolean numero = key >= 48 && key <=57;
        if(!numero){
            evt.consume();
        }
    }//GEN-LAST:event_txtDNIKeyPressed

    private void cbxCargoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCargoItemStateChanged
       if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
           if(cbxCargo.getSelectedIndex()==1)
                txtCod.setVisible(true);
           else
                txtCod.setVisible(false);
       
       }
    }//GEN-LAST:event_cbxCargoItemStateChanged

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void btnEditarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEmpActionPerformed
        
        int i = listCodigo.getSelectedIndex();
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!",
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        //agregar funcion de opciones y poner el editar
        if(resp==0){
            
            per = oemp.buscarCliente(Integer.parseInt(txtDNI.getText()));
            enviar(per);
            oemp.grabar();
            limpiar_model();
            llena();
            edit(false);
            estado_btn(false, true, false, false, true);
        }
        
    }//GEN-LAST:event_btnEditarEmpActionPerformed

    private void obtener(Persona p){
        txtCodigo.setText(((Empleado)p).getCodigo()+"");
        txtDNI.setText(p.getDNI()+"");
        txtNombre.setText(p.getNombre());
        txtApellido.setText(p.getApellido());
        cbxCargo.setSelectedItem(((Empleado)p).getCargo());
        txtCod.setText(((Empleado)p).getCodD()+"");
        if(cbxCargo.getSelectedIndex()==1)  txtCod.setVisible(true);
        else  txtCod.setVisible(false);
        txtContrasena.setText(((Empleado)p).getContraseña());
    }
    private void enviar(Persona p){
        ((Empleado)p).setCodigo(Integer.parseInt(txtCodigo.getText()));
        p.setDNI(Integer.parseInt(txtDNI.getText()));
        p.setNombre(txtNombre.getText());
        p.setApellido(txtApellido.getText());
        ((Empleado)p).setCargo(cbxCargo.getSelectedItem().toString());
        ((Empleado)p).setCodD(Integer.parseInt(txtCod.getText()));
        ((Empleado)p).setContraseña(crip.cripto(txtContrasena.getText()));
    }
    
    private void btnNuevoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEmpActionPerformed
        limpiar();
        estado_btn(true,false,false,false, true);
        edit(true);
        if (oemp.getCorrelativo()==0)
        {
            txtCodigo.setText(1+"");
        }
        else{
            txtCodigo.setText(oemp.getCorrelativo()+"");
        }
    }//GEN-LAST:event_btnNuevoEmpActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       //definir el formato de la fecha
       LocalDateTime ldt = LocalDateTime.now();
       String fecha = ldt.format(formato_Fec);
       // obtener los datos ingresados a traves del formulario
       int codD=0;
       if(cbxCargo.getSelectedIndex()==1) codD = Integer.parseInt(txtCod.getText());
       else codD = 0;
       String nom = txtNombre.getText();
       String ape = txtApellido.getText();
       String cargo = cbxCargo.getSelectedItem().toString();
       String pass = crip.cripto(txtContrasena.getText());
       
       int validar_dni = oemp.buscarDNI(Integer.parseInt(txtDNI.getText()));
       int est =1;
       int validar = validad(txtDNI.getText(),nom, ape,cargo,pass);

       if(validar_dni!=-1)
           JOptionPane.showMessageDialog(null,"Usuario registrado");
       if(validar ==0 && validar_dni==-1){
           //int DNI, String nombre, String apellido,String anio, int codigo, String cargo, int estado,int codD, String contraseña)
           //al ser parseados, necesariamente deben tener un valor ingresado
            int cod = Integer.parseInt(txtCodigo.getText());
            int dni = Integer.parseInt(txtDNI.getText());
            Persona p = new Empleado(dni,nom,ape,fecha,cod, cargo,est,codD,pass);
            oemp.adicionar((Empleado)p);
            limpiar_model();
            llena();
            txtCodigo.setText(oemp.getCorrelativo()+1+"");
            oemp.grabar();
            edit(false);
            estado_btn(false,true,false,false, true);
       }
       else{
            System.out.println(""+validar);
            JOptionPane.showMessageDialog(null,"faltan datos");
       }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarEmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmp1ActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!",
                JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if(resp==1){
        }
        else{
            per = oemp.buscarCliente(Integer.parseInt(txtDNI.getText()));
            //System.out.println(i);
            oemp.eliminar(per);
            oemp.grabar();
            limpiar_model();
            llena();
            edit(false);
            estado_btn(false,true,false,false, true);
        }
    }//GEN-LAST:event_btnEliminarEmp1ActionPerformed

    private void jpopEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpopEditActionPerformed
        
        if(listCodigo.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null,"Por favor, Seleccione un codigo");
        }
        else{
            estado_btn(false,false,true,true, true);
            
            int i = listCodigo.getSelectedIndex();
            obtener(oemp.obtener(i));
            edit(true);
            cbxCargo.setEnabled(false);
        }
    }//GEN-LAST:event_jpopEditActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void listCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCodigoMouseClicked
        int i = listCodigo.getSelectedIndex();
        listNombres.setSelectedIndex(i);
        listNombres.setSelectedIndex(i);
        listApellidos.setSelectedIndex(i);
        ListCargo.setSelectedIndex(i);
        ListCod.setSelectedIndex(i);
        ListAnio.setSelectedIndex(i);
    }//GEN-LAST:event_listCodigoMouseClicked

    private void txtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyTyped
       int key = evt.getKeyChar();
        boolean numero = key >= 48 && key <=57;
        if(!numero){
            evt.consume();
        }
    }//GEN-LAST:event_txtDNIKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListAnio;
    private javax.swing.JList<String> ListCargo;
    private javax.swing.JList<String> ListCod;
    private javax.swing.JButton btnEditarEmp;
    private javax.swing.JButton btnEliminarEmp1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevoEmp;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxCargo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JMenuItem jpopEdit;
    private javax.swing.JList<String> listApellidos;
    private javax.swing.JList<String> listCodigo;
    private javax.swing.JList<String> listNombres;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
