/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.ClienteDAO;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author david
 */
public class frmPrincipal extends javax.swing.JFrame {
    ClienteDAO oclie=new ClienteDAO("Clientes.txt");
    DateTimeFormatter formateador = DateTimeFormatter.ofPattern("HH:mm:ss");
    public static Object[] user= frmLogin.user;
    public frmPrincipal() {
        initComponents();
        frmLogin.user=null;
        setLocationRelativeTo(null);
        //acceso(user);
        nombre();
        hora();
        
    }
    private void acceso(Object[] user){
       btnFrmTratamiento.setVisible(false);
       btnFrmEmpleado.setVisible(false);
       jtxtMedico.setVisible(false);
    }
    
    private void nombre(){
        if(user!=null){
            jtxtnom.setText(user[0].toString());
            jtxtcargo.setText(user[1].toString());
        }
        else{
            //nom, cargo, dni
            user = new String[]{"david1","asistente","999"};
            jtxtnom.setText(user[0].toString());
            jtxtcargo.setText(user[1].toString());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnFrmEmpleado = new javax.swing.JButton();
        btnFrmCita = new javax.swing.JButton();
        btnFrmBuscarCli = new javax.swing.JButton();
        btnFrmPaciente = new javax.swing.JButton();
        btnFrmTratamiento = new javax.swing.JButton();
        jtxtnom = new javax.swing.JLabel();
        jtxtcargo = new javax.swing.JLabel();
        jtxtHora = new javax.swing.JLabel();
        jtxtMedico = new javax.swing.JLabel();
        jtxtAsistente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jDesktopPane1.setDoubleBuffered(true);

        btnFrmEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnFrmEmpleado.setText("Empleado");
        btnFrmEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrmEmpleadoActionPerformed(evt);
            }
        });

        btnFrmCita.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnFrmCita.setText("Cita");
        btnFrmCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrmCitaActionPerformed(evt);
            }
        });

        btnFrmBuscarCli.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnFrmBuscarCli.setText("Buscar Cliente");
        btnFrmBuscarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrmBuscarCliActionPerformed(evt);
            }
        });

        btnFrmPaciente.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnFrmPaciente.setText("Paciente");
        btnFrmPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrmPacienteActionPerformed(evt);
            }
        });

        btnFrmTratamiento.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnFrmTratamiento.setText("Tratamiento");
        btnFrmTratamiento.setPreferredSize(new java.awt.Dimension(222, 50));
        btnFrmTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrmTratamientoActionPerformed(evt);
            }
        });

        jtxtnom.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtnom.setText("David");

        jtxtcargo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtcargo.setText("Asistente");

        jtxtHora.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jtxtHora.setForeground(new java.awt.Color(255, 0, 0));
        jtxtHora.setText("HH:MM:SS");

        jtxtMedico.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtMedico.setText("Medico");

        jtxtAsistente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtAsistente.setText("Asistente");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("falta  Tratamiento");

        jDesktopPane1.setLayer(btnFrmEmpleado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnFrmCita, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnFrmBuscarCli, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnFrmPaciente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnFrmTratamiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtxtnom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtxtcargo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtxtHora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtxtMedico, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtxtAsistente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jtxtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jtxtAsistente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnFrmPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnFrmCita, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnFrmBuscarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 374, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jtxtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnFrmTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnFrmEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(196, 196, 196))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtAsistente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jtxtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnFrmPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFrmTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFrmCita, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFrmEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFrmBuscarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)))
                .addGap(203, 203, 203)
                .addComponent(jtxtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jtxtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void hora(){
        Runnable runnable = new Runnable() {
        @Override
        public void run() {
            while (true) {
                try {
                    Thread.sleep(500);
                    jtxtHora.setText(formateador.format(LocalDateTime.now()));
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }
        };
        Thread hilo = new Thread(runnable);
        hilo.start();
    }
    
    private void btnFrmBuscarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrmBuscarCliActionPerformed
        
        frmBuscarCliente m = new frmBuscarCliente();
        m.setClosable(true);
        m.setResizable(false);
        jDesktopPane1.add(m);
        m.setVisible(true);
        
    }//GEN-LAST:event_btnFrmBuscarCliActionPerformed

    private void btnFrmCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrmCitaActionPerformed
       
        frmCita m = new frmCita();
        
        m.setClosable(true);
        m.setResizable(false);
        jDesktopPane1.add(m);
        m.setVisible(true);
        
    }//GEN-LAST:event_btnFrmCitaActionPerformed

    private void btnFrmPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrmPacienteActionPerformed
        
        frmPaciente m = new frmPaciente();
        m.setClosable(true);
        m.setResizable(false);
        jDesktopPane1.add(m);
        m.setVisible(true);
        
        
    }//GEN-LAST:event_btnFrmPacienteActionPerformed

    private void btnFrmEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrmEmpleadoActionPerformed
    
        frmEmpleado m = new frmEmpleado();
        m.setClosable(false);
        jDesktopPane1.add(m);
        m.setResizable(false);
        m.setVisible(true);
        
    }//GEN-LAST:event_btnFrmEmpleadoActionPerformed

    private void btnFrmTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrmTratamientoActionPerformed
        frmTratamiento m = new frmTratamiento();
        m.setClosable(true);
        m.setResizable(false);
        jDesktopPane1.add(m);
        m.setVisible(true);
    }//GEN-LAST:event_btnFrmTratamientoActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFrmBuscarCli;
    private javax.swing.JButton btnFrmCita;
    private javax.swing.JButton btnFrmEmpleado;
    private javax.swing.JButton btnFrmPaciente;
    private javax.swing.JButton btnFrmTratamiento;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jtxtAsistente;
    private javax.swing.JLabel jtxtHora;
    private javax.swing.JLabel jtxtMedico;
    private javax.swing.JLabel jtxtcargo;
    private javax.swing.JLabel jtxtnom;
    // End of variables declaration//GEN-END:variables
}
