/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import Controllers.ClienteDAO;

import Models.Cliente;
import Models.Persona;
import java.text.ParseException;
import java.text.SimpleDateFormat;  
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author david
 */
public final class frmPaciente extends javax.swing.JInternalFrame {
    ClienteDAO oclie=new ClienteDAO("Clientes.txt");
    DefaultTableModel dtmPaciente= new DefaultTableModel();
    TableRowSorter<DefaultTableModel> sorter;
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    Persona per = new Cliente();    
    int registro_dni=-1;
    String genero="";
    public frmPaciente() {

        initComponents();
        grupoGenero();
        llenaCabecera();
        llena();
        edit(false);
        estado_btn(true,false,false,true);
    }

    public void llenaCabecera(){
        dtmPaciente.addColumn("DNI");
        dtmPaciente.addColumn("Nombres");
        dtmPaciente.addColumn("Apellidos");
        dtmPaciente.addColumn("Edad");
        dtmPaciente.addColumn("Genero");
        dtmPaciente.addColumn("Direccion");
        
        jtblCliente.setModel(dtmPaciente);
        jtblCliente.setAutoCreateRowSorter(true);
        sorter = new TableRowSorter<>(dtmPaciente);
        jtblCliente.setRowSorter(sorter);

    }
    public void llena(){
        if (oclie.tamaño() == 0) {
            JOptionPane.showMessageDialog(this, "Lista sin Elementos!", "Validar", 2);
        } else {
            dtmPaciente.setRowCount(0);//Limpia las filas del JTable
            for (int i = 0; i < oclie.tamaño(); i++) {
                Object vec[] = new Object[6];
                vec[0] = oclie.obtener(i).getDNI();
                vec[1] = oclie.obtener(i).getNombre();
                vec[2] = oclie.obtener(i).getApellido();
                vec[3] = oclie.obtener(i).getAnio();
                vec[4] = ((Cliente)oclie.obtener(i)).getSexo();
                vec[5] = ((Cliente)oclie.obtener(i)).getDirreccion();
                //Agregar elementos al JTable
                dtmPaciente.addRow(vec);
            }
            jtblCliente.setModel(dtmPaciente);
        }
    }
    
    private void grupoGenero(){
        RbtnGrupo.add(jRbtnH);
        RbtnGrupo.add(jRbtnM);
        RbtnGrupo.add(jRbtnO);
    }
    private void estado_btn(boolean btnB,boolean btnG,boolean btnM,boolean btnN){
        btnBuscar.setEnabled(btnB);
        btnGuardar.setEnabled(btnG);
        btnModificar.setEnabled(btnM);
        btnNuevo.setEnabled(btnN);
    }
    private void estado_radio(boolean estH,boolean estM,boolean estO){
        jRbtnH.setSelected(estH);
        jRbtnM.setSelected(estM);
        jRbtnO.setSelected(estO);
    }
    private void limpiar(){
        jtxtDNI.setText("");
        txtNom.setText("");
        txtApe.setText("");
        txtaDir.setText("");
        jdcNac.setCalendar(null);
    }
    private int validad(String nombre, String apellido, String dirreccion, String fec_nac, String sexo){
        int i =0;
        if(nombre.equals("")){
           i++; 
        }
        if(apellido.equals("")){
           i++; 
        }
        if(dirreccion.equals("")){
           i++; 
        }
        if(fec_nac.isEmpty()){
           i++; 
        }
        if(sexo.equals("no definido")){
           i++; 
        }
        return i;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RbtnGrupo = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        popEdit = new javax.swing.JMenuItem();
        popDel = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jtxtDNI = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtApe = new javax.swing.JTextField();
        jdcNac = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jRbtnH = new javax.swing.JRadioButton();
        jRbtnM = new javax.swing.JRadioButton();
        jRbtnO = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaDir = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblCliente = new javax.swing.JTable();

        popEdit.setText("editar");
        popEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popEditActionPerformed(evt);
            }
        });
        jPopupMenu1.add(popEdit);

        popDel.setText("eliminar");
        popDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popDelActionPerformed(evt);
            }
        });
        jPopupMenu1.add(popDel);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)), "Datos Tratante"));

        jtxtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDNIKeyTyped(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Genero"));

        RbtnGrupo.add(jRbtnH);
        jRbtnH.setText("Hombre");

        RbtnGrupo.add(jRbtnM);
        jRbtnM.setText("Mujer");

        RbtnGrupo.add(jRbtnO);
        jRbtnO.setText("Otros");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRbtnH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRbtnM, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRbtnO, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRbtnH)
                    .addComponent(jRbtnM)
                    .addComponent(jRbtnO))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Fecha Nacimiento");

        jLabel3.setText("Direccion");

        jLabel4.setText("DNI");

        jLabel5.setText("nombre");

        txtaDir.setColumns(20);
        txtaDir.setRows(5);
        jScrollPane2.setViewportView(txtaDir);

        jLabel6.setText("Apellidos");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jdcNac, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(txtNom))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtApe, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addComponent(txtApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        btnGuardar.setText("Grabar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 540));

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jtblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblCliente = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jtblCliente.setComponentPopupMenu(jPopupMenu1);
        jtblCliente.getTableHeader().setResizingAllowed(false);
        jtblCliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jtblCliente);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 620, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      
        if(jtxtDNI.getText().isEmpty()){ // si esta vacio
            JOptionPane.showMessageDialog(null,"Por favor, ingresa un N° de DNI");
        }
        else{ // si esta vacio
            if(jtblCliente.getRowCount() == 0){
                JOptionPane.showMessageDialog(null,"la tabla esta vacia.");
            }
            else{
                int dni=Integer.parseInt(jtxtDNI.getText());
                int index=oclie.buscarDNI(dni);
                if(index==-1){
                    JOptionPane.showMessageDialog(null,"No se encuentra resgistrado.","Notificacion de Busqueda",1);
                }
                else{
                    registro_dni=1;
                    jtblCliente.clearSelection();
                    jtblCliente.changeSelection(index, 0, closable, isIcon);
                }              
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
        edit(true);
        estado_radio(true,true,true);
        estado_btn(false,true,false,false);
        RbtnGrupo.clearSelection();
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        if(jtxtDNI.getText().equals("")){
            JOptionPane.showMessageDialog(null,"ingresa el DNI");
        }
        else{
                int dni = Integer.parseInt(jtxtDNI.getText());
                int index=oclie.buscarDNI(dni);
                //-1 se procede con el registro
                //else no se puede
                if(index==-1){
                    String nom = txtNom.getText();
                    String ape = txtApe.getText();
                    String dir = txtaDir.getText();

                    String nac = formato.format(jdcNac.getDate());
                    genero = genero();
                    int validar = validad(nom, ape, dir, nac, genero);
                    if (validar == 0) {
                        Persona p = new Cliente(dni, nom, ape, nac, dir, genero);
                        oclie.adicionar((Cliente) p);
                        llena();
                        oclie.grabar();
                        estado_radio(false, false, false);
                        estado_btn(true, false, false, true);
                        edit(false);
                        RbtnGrupo.clearSelection();
                        jtxtDNI.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "faltan datos");
                    }
                }
                else{
                   JOptionPane.showMessageDialog(null,"El cliente esta resgistrado.","Notificacion de Registro",1); 
                } 
 
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void popEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popEditActionPerformed
        int row = jtblCliente.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(null,"Por favo seleecionar una fila","Notificacion", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            estado_btn(false, false, true, false);
            jtblCliente.setEnabled(false);
            try {

                jtxtDNI.setText(dtmPaciente.getValueAt(row, 0).toString());
                txtNom.setText(dtmPaciente.getValueAt(row, 1).toString());
                txtApe.setText(dtmPaciente.getValueAt(row, 2).toString());
                txtaDir.setText(dtmPaciente.getValueAt(row, 5).toString());
                jdcNac.setDate(formato.parse(dtmPaciente.getValueAt(row, 3).toString()));
                String gen = dtmPaciente.getValueAt(row, 4).toString();
                if (gen.equals("Mujer")) {
                    estado_radio(false, true, false);
                } else if (gen.equals("Hombre")) {
                    estado_radio(true, false, false);
                } else if (gen.equals("no definido")) {
                    estado_radio(false, false, true);
                }
                edit(true);
            } catch (ParseException ex) {
                Logger.getLogger(frmPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_popEditActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //modificar los valores del puntero hacia la clase
        int dni = Integer.parseInt(jtxtDNI.getText());
        per=oclie.buscarCliente(dni);
        // String nombre, String apellido,String anio, String dirreccion, String sexo
        per.setDNI(dni);
        per.setNombre(txtNom.getText());
        per.setApellido(txtApe.getText());
        per.setAnio(formato.format(jdcNac.getDate()));
        ((Cliente)per).setDirreccion(txtaDir.getText());
        ((Cliente)per).setSexo(genero());

        oclie.grabar();
        llena();
        //modificaciones visual interfaz
        //modifar los accesos, faltan declarar el comportamiento de los enabled
        estado_btn(true,false,false,true);
        jtblCliente.setEnabled(true);
        limpiar();
        edit(false);
        RbtnGrupo.clearSelection();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        per=null;
        RbtnGrupo.clearSelection();
        edit(false);
        limpiar();
        estado_btn(true,false,false,true);
        jtblCliente.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void popDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popDelActionPerformed
        int i= JOptionPane.showConfirmDialog(this, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION,JOptionPane.ERROR_MESSAGE);
        if(i==1){
            int row = jtblCliente.getSelectedRow();
            int dni = parseInt(dtmPaciente.getValueAt(row, 0).toString());
            per=oclie.buscarCliente(dni);
            oclie.eliminar(per);
            oclie.grabar();
            llena(); 
        }

    }//GEN-LAST:event_popDelActionPerformed

    private void jtxtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDNIKeyTyped
        int key = evt.getKeyChar();
        boolean numero = key >= 48 && key <=57;
        if(!numero){
            evt.consume();
        }
        if (jtxtDNI.getText().trim().length() == 8) {
        evt.consume();
        }
    }//GEN-LAST:event_jtxtDNIKeyTyped

    private String genero(){
        if(jRbtnH.isSelected()){ return "Hombre";}
        else if(jRbtnM.isSelected()){ return "Mujer";}
        else if(jRbtnO.isSelected()){ return "otros Generos";}
        else{ return "no definido";}
    }
    private void edit(boolean est){
        txtNom.setEnabled(est);
        txtApe.setEnabled(est);
        txtaDir.setEnabled(est);
        jdcNac.setEnabled(est);
        jRbtnH.setEnabled(est);
        jRbtnM.setEnabled(est);
        jRbtnO.setEnabled(est);
    }

    private int parseInt(String text){
        return Integer.parseInt(text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup RbtnGrupo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRbtnH;
    private javax.swing.JRadioButton jRbtnM;
    private javax.swing.JRadioButton jRbtnO;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdcNac;
    private javax.swing.JTable jtblCliente;
    private javax.swing.JTextField jtxtDNI;
    private javax.swing.JMenuItem popDel;
    private javax.swing.JMenuItem popEdit;
    private javax.swing.JTextField txtApe;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextArea txtaDir;
    // End of variables declaration//GEN-END:variables
}
